language: csharp
mono: none
dotnet: 2.1.105
solution: CitadelCore.sln
env:
  global:
    secure: Bi6j2/XzkvqRLcJQx9J6QUo4AnqGeuylEcb5fRDTEIiozwAcpyyj/2jw6KEHdDkgXmk1Hu/QUw1BCkLXUmlpgt0SeiEjUOiHG9cZnPYetzQeLXsG1QaE7gz86SF9ErUiduw3CdzMmrhJe3bdr6Fg5YU+evXPTd73lJMLPhj6d6RGge7LrxRPRs22mXWNM+7nYp44AoQax7iCjdFl07kY3M+3qQnkE6sszwb743YSicHuMP6BYn+NPY09Dk2BwQdFLB1I2bOaEPOf53Un/OZnolYIHMCdawuSw90g2CGuXFfc54NguSHjw54en0Gy46W5xzTvOVVMS88FE0r47n7okBQLzj5E7XGMYqrVqtno/nczrVyE3zEx7cBi/s0C1KbjNxRuCXnDBIGXbNtOrWchWy8JdKop1a2qCpaijEa8a9wPxAiHUtra+/nc52Uhkd9es6KRc/p+wLV2XOvBFg8cBReIR0z5NQnm3ZzgpdgUsxR7turofvZIEcsFm7JKqDsdkXGOwLREzi9X9fl2CPO20jk071jXCkVzGsM+CMO3iM/dO2QmQx1CS4Cqis+S5/2chgDIRfLwTcNmasf0Acwr5y8wln+scND7UHEM76jfjNnjGtF4qY8Vz+vl9xJoGbM9alJTs2LqrcVyEAi1jaq6yRLC+NotZFAL4I0gXRgy+f0=
before_install:
- echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN
  CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

script: dotnet clean && dotnet build --configuration Release
